services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # Добавленный healthcheck
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_auth"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/fastapi_auth
    depends_on:
      db:
        condition: service_healthy  # Теперь healthcheck есть
    volumes:
      - ./app:/app
    restart: unless-stopped

volumes:
  postgres_data: